### ISSUE TITLE
No overlays are shown

### ISSUE THREAD

**Issue by MMinga** [armbian/configng#344]
### What happened?

There is now possibilty to change settings when nothing is shown.
![Screenshot 2024-12-27 184816](https://github.com/user-attachments/assets/d39871c6-07d2-472b-8aad-bbc451e31928)
![Screenshot 2024-12-27 184925](https://github.com/user-attachments/assets/43d67d57-2924-4981-9d11-63ec89f129f5)

### How to reproduce?

no description needed it never has shown devices.

### On which host OS are you running the build script and observing this problem?

Ubuntu 22.04 Jammy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tearran** [comment]
works on `meson`
```
armbian-config --api manage_dtoverlays
```
<img width="677" alt="{403726A5-81DA-4867-A957-B20322B479A8}" src="https://github.com/user-attachments/assets/949bca16-6d3d-449d-a354-b8f0aa891871" />

**Comment by igorpecovnik** [comment]
This should be fixed. I have tried with latest Bookworm image + latest armbian-config (on Odroid M1). 

![Image](https://github.com/user-attachments/assets/91fdc714-9a0d-4f45-a432-3058084d0fc2)

Try update everything and if it still doesn't work, provide info from:

```
sudo apt -y install tree
tree /boot/dtb/
cat /boot/armbianEnv.txt
```

**Comment by sp2ong** [comment]
**On Orange Pi Zero V1** after update & upgrade when selecting Manage oerlays from armbian-config not see my selected modules in overlays= in armbianEnv.txt so I selected again but still added overlay_prefix to modules in overlays= and after reboot no modules loaded. When removing manually overlay prefix form names modules in overlaus= all works
OK

_v25.2 rolling for Orange Pi Zero running Armbian Linux 6.6.72-current-sunxi_


_cat /boot/armbianEnv.txt 
verbosity=1
bootlogo=false
console=both
disp_mode=1920x1080p60
overlay_prefix=sun8i-h3
overlays=sun8i-h3-analog-codec sun8i-h3-i2c0 sun8i-h3-uart1 sun8i-h3-uart2 sun8i-h3-usbhost2 sun8i-h3-usbhost3
rootdev=UUID=79665e18-ad8c-4276-a34d-3b181f8f6fac
rootfstype=ext4
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u_



tree /boot/dtb/
/boot/dtb/
├── overlay
│   ├── README.sun4i-a10-overlays
│   ├── README.sun5i-a13-overlays
│   ├── README.sun7i-a20-overlays
│   ├── README.sun8i-h3-overlays
│   ├── sun4i-a10-analog-codec.dtbo
│   ├── sun4i-a10-can.dtbo
│   ├── sun4i-a10-fixup.scr
│   ├── sun4i-a10-i2c1.dtbo
│   ├── sun4i-a10-i2c2.dtbo
│   ├── sun4i-a10-nand.dtbo
│   ├── sun4i-a10-pps-gpio.dtbo
│   ├── sun4i-a10-pwm.dtbo
│   ├── sun4i-a10-spdif-out.dtbo
│   ├── sun4i-a10-spi-jedec-nor.dtbo
│   ├── sun4i-a10-spi-spidev.dtbo
│   ├── sun4i-a10-uart2.dtbo
│   ├── sun4i-a10-uart3.dtbo
│   ├── sun4i-a10-uart4.dtbo
│   ├── sun4i-a10-uart5.dtbo
│   ├── sun4i-a10-uart6.dtbo
│   ├── sun4i-a10-uart7.dtbo
│   ├── sun4i-a10-w1-gpio.dtbo
│   ├── sun5i-a13-analog-codec.dtbo
│   ├── sun5i-a13-fixup.scr
│   ├── sun5i-a13-i2c1.dtbo
│   ├── sun5i-a13-i2c2.dtbo
│   ├── sun5i-a13-nand.dtbo
│   ├── sun5i-a13-pwm.dtbo
│   ├── sun5i-a13-spi0.dtbo
│   ├── sun5i-a13-spi1.dtbo
│   ├── sun5i-a13-spi2.dtbo
│   ├── sun5i-a13-spi-jedec-nor.dtbo
│   ├── sun5i-a13-spi-spidev.dtbo
│   ├── sun5i-a13-uart0.dtbo
│   ├── sun5i-a13-uart1.dtbo
│   ├── sun5i-a13-uart2.dtbo
│   ├── sun5i-a13-uart3.dtbo
│   ├── sun7i-a20-analog-codec.dtbo
│   ├── sun7i-a20-can.dtbo
│   ├── sun7i-a20-fixup.scr
│   ├── sun7i-a20-i2c1.dtbo
│   ├── sun7i-a20-i2c2.dtbo
│   ├── sun7i-a20-i2c3.dtbo
│   ├── sun7i-a20-i2c4.dtbo
│   ├── sun7i-a20-mmc2.dtbo
│   ├── sun7i-a20-nand.dtbo
│   ├── sun7i-a20-pps-gpio.dtbo
│   ├── sun7i-a20-pwm.dtbo
│   ├── sun7i-a20-spdif-out.dtbo
│   ├── sun7i-a20-spi-add-cs1.dtbo
│   ├── sun7i-a20-spi-jedec-nor.dtbo
│   ├── sun7i-a20-spi-spidev.dtbo
│   ├── sun7i-a20-uart2.dtbo
│   ├── sun7i-a20-uart3.dtbo
│   ├── sun7i-a20-uart4.dtbo
│   ├── sun7i-a20-uart5.dtbo
│   ├── sun7i-a20-uart6.dtbo
│   ├── sun7i-a20-uart7.dtbo
│   ├── sun7i-a20-w1-gpio.dtbo
│   ├── sun8i-h3-analog-codec.dtbo
│   ├── sun8i-h3-cir.dtbo
│   ├── sun8i-h3-cpu-clock-1.2GHz-1.3v.dtbo
│   ├── sun8i-h3-cpu-clock-1.368GHz-1.3v.dtbo
│   ├── sun8i-h3-cpu-clock-1.3GHz-1.3v.dtbo
│   ├── sun8i-h3-fixup.scr
│   ├── sun8i-h3-i2c0.dtbo
│   ├── sun8i-h3-i2c1.dtbo
│   ├── sun8i-h3-i2c2.dtbo
│   ├── sun8i-h3-pps-gpio.dtbo
│   ├── sun8i-h3-pwm.dtbo
│   ├── sun8i-h3-spdif-out.dtbo
│   ├── sun8i-h3-spi-add-cs1.dtbo
│   ├── sun8i-h3-spi-jedec-nor.dtbo
│   ├── sun8i-h3-spi-spidev.dtbo
│   ├── sun8i-h3-tve.dtbo
│   ├── sun8i-h3-uart1.dtbo
│   ├── sun8i-h3-uart2.dtbo
│   ├── sun8i-h3-uart3.dtbo
│   ├── sun8i-h3-usbhost0.dtbo
│   ├── sun8i-h3-usbhost1.dtbo
│   ├── sun8i-h3-usbhost2.dtbo
│   ├── sun8i-h3-usbhost3.dtbo
│   ├── sun8i-h3-w1-gpio.dtbo
│   ├── sun8i-r40-i2c2.dtbo
│   ├── sun8i-r40-i2c3.dtbo
│   ├── sun8i-r40-spi-spidev0.dtbo
│   ├── sun8i-r40-spi-spidev1.dtbo
│   ├── sun8i-r40-uart2.dtbo
│   ├── sun8i-r40-uart4.dtbo
│   ├── sun8i-r40-uart5.dtbo
│   └── sun8i-r40-uart7.dtbo
├── sun4i-a10-a1000.dtb
├── sun4i-a10-ba10-tvbox.dtb
├── sun4i-a10-chuwi-v7-cw0825.dtb
├── sun4i-a10-cubieboard.dtb
├── sun4i-a10-dserve-dsrv9703c.dtb
├── sun4i-a10-gemei-g9.dtb
├── sun4i-a10-hackberry.dtb
├── sun4i-a10-hyundai-a7hd.dtb
├── sun4i-a10-inet1.dtb
├── sun4i-a10-inet97fv2.dtb
├── sun4i-a10-inet9f-rev03.dtb
├── sun4i-a10-itead-iteaduino-plus.dtb
├── sun4i-a10-jesurun-q5.dtb
├── sun4i-a10-marsboard.dtb
├── sun4i-a10-mini-xplus.dtb
├── sun4i-a10-mk802.dtb
├── sun4i-a10-mk802ii.dtb
├── sun4i-a10-olinuxino-lime.dtb
├── sun4i-a10-pcduino2.dtb
├── sun4i-a10-pcduino.dtb
├── sun4i-a10-pov-protab2-ips9.dtb
├── sun4i-a10-topwise-a721.dtb
├── sun5i-a10s-auxtek-t003.dtb
├── sun5i-a10s-auxtek-t004.dtb
├── sun5i-a10s-mk802.dtb
├── sun5i-a10s-olinuxino-micro.dtb
├── sun5i-a10s-r7-tv-dongle.dtb
├── sun5i-a10s-wobo-i5.dtb
├── sun5i-a13-difrnce-dit4350.dtb
├── sun5i-a13-empire-electronix-d709.dtb
├── sun5i-a13-empire-electronix-m712.dtb
├── sun5i-a13-hsg-h702.dtb
├── sun5i-a13-inet-98v-rev2.dtb
├── sun5i-a13-licheepi-one.dtb
├── sun5i-a13-olinuxino.dtb
├── sun5i-a13-olinuxino-micro.dtb
├── sun5i-a13-pocketbook-touch-lux-3.dtb
├── sun5i-a13-q8-tablet.dtb
├── sun5i-a13-utoo-p66.dtb
├── sun5i-gr8-chip-pro.dtb
├── sun5i-gr8-evb.dtb
├── sun5i-r8-chip.dtb
├── sun6i-a31-app4-evb1.dtb
├── sun6i-a31-colombus.dtb
├── sun6i-a31-hummingbird.dtb
├── sun6i-a31-i7.dtb
├── sun6i-a31-m9.dtb
├── sun6i-a31-mele-a1000g-quad.dtb
├── sun6i-a31s-colorfly-e708-q1.dtb
├── sun6i-a31s-cs908.dtb
├── sun6i-a31s-inet-q972.dtb
├── sun6i-a31s-primo81.dtb
├── sun6i-a31s-sina31s.dtb
├── sun6i-a31s-sinovoip-bpi-m2.dtb
├── sun6i-a31s-yones-toptech-bs1078-v2.dtb
├── sun7i-a20-bananapi.dtb
├── sun7i-a20-bananapi-m1-plus.dtb
├── sun7i-a20-bananapro.dtb
├── sun7i-a20-cubieboard2.dtb
├── sun7i-a20-cubietruck.dtb
├── sun7i-a20-haoyu-marsboard.dtb
├── sun7i-a20-hummingbird.dtb
├── sun7i-a20-i12-tvbox.dtb
├── sun7i-a20-icnova-a20-adb4006.dtb
├── sun7i-a20-icnova-swac.dtb
├── sun7i-a20-itead-ibox.dtb
├── sun7i-a20-lamobo-r1.dtb
├── sun7i-a20-linutronix-testbox-v2.dtb
├── sun7i-a20-m3.dtb
├── sun7i-a20-mk808c.dtb
├── sun7i-a20-olimex-som204-evb.dtb
├── sun7i-a20-olimex-som204-evb-emmc.dtb
├── sun7i-a20-olimex-som-evb.dtb
├── sun7i-a20-olimex-som-evb-emmc.dtb
├── sun7i-a20-olinuxino-lime2.dtb
├── sun7i-a20-olinuxino-lime2-emmc.dtb
├── sun7i-a20-olinuxino-lime.dtb
├── sun7i-a20-olinuxino-lime-emmc.dtb
├── sun7i-a20-olinuxino-micro.dtb
├── sun7i-a20-olinuxino-micro-emmc.dtb
├── sun7i-a20-orangepi.dtb
├── sun7i-a20-orangepi-mini.dtb
├── sun7i-a20-pcduino3.dtb
├── sun7i-a20-pcduino3-nano.dtb
├── sun7i-a20-wexler-tab7200.dtb
├── sun7i-a20-wits-pro-a20-dkt.dtb
├── sun8i-a23-evb.dtb
├── sun8i-a23-gt90h-v4.dtb
├── sun8i-a23-inet86dz.dtb
├── sun8i-a23-ippo-q8h-v1.2.dtb
├── sun8i-a23-ippo-q8h-v5.dtb
├── sun8i-a23-polaroid-mid2407pxe03.dtb
├── sun8i-a23-polaroid-mid2809pxe04.dtb
├── sun8i-a23-q8-tablet.dtb
├── sun8i-a33-et-q8-v1.6.dtb
├── sun8i-a33-ga10h-v1.1.dtb
├── sun8i-a33-inet-d978-rev2.dtb
├── sun8i-a33-ippo-q8h-v1.2.dtb
├── sun8i-a33-olinuxino.dtb
├── sun8i-a33-q8-tablet.dtb
├── sun8i-a33-sinlinx-sina33.dtb
├── sun8i-a83t-allwinner-h8homlet-v2.dtb
├── sun8i-a83t-bananapi-m3.dtb
├── sun8i-a83t-cubietruck-plus.dtb
├── sun8i-a83t-tbs-a711.dtb
├── sun8i-h2-plus-bananapi-m2-zero.dtb
├── sun8i-h2-plus-libretech-all-h3-cc.dtb
├── sun8i-h2-plus-nanopi-duo.dtb
├── sun8i-h2-plus-orangepi-r1.dtb
├── sun8i-h2-plus-orangepi-zero.dtb
├── sun8i-h2-plus-sunvell-r69.dtb
├── sun8i-h3-bananapi-m2-plus.dtb
├── sun8i-h3-bananapi-m2-plus-v1.2.dtb
├── sun8i-h3-beelink-x2.dtb
├── sun8i-h3-emlid-neutis-n5h3-devboard.dtb
├── sun8i-h3-libretech-all-h3-cc.dtb
├── sun8i-h3-mapleboard-mp130.dtb
├── sun8i-h3-nanopi-duo2.dtb
├── sun8i-h3-nanopi-m1.dtb
├── sun8i-h3-nanopi-m1-plus.dtb
├── sun8i-h3-nanopi-neo-air.dtb
├── sun8i-h3-nanopi-neo.dtb
├── sun8i-h3-nanopi-r1.dtb
├── sun8i-h3-orangepi-2.dtb
├── sun8i-h3-orangepi-lite.dtb
├── sun8i-h3-orangepi-one.dtb
├── sun8i-h3-orangepi-pc.dtb
├── sun8i-h3-orangepi-pc-plus.dtb
├── sun8i-h3-orangepi-plus2e.dtb
├── sun8i-h3-orangepi-plus.dtb
├── sun8i-h3-orangepi-zero-plus2.dtb
├── sun8i-h3-rervision-dvk.dtb
├── sun8i-h3-zeropi.dtb
├── sun8i-r16-bananapi-m2m.dtb
├── sun8i-r16-nintendo-nes-classic.dtb
├── sun8i-r16-nintendo-super-nes-classic.dtb
├── sun8i-r16-parrot.dtb
├── sun8i-r40-bananapi-m2-ultra.dtb
├── sun8i-r40-oka40i-c.dtb
├── sun8i-s3-elimo-initium.dtb
├── sun8i-s3-lichee-zero-plus.dtb
├── sun8i-s3-pinecube.dtb
├── sun8i-t113s-mangopi-mq-r-t113.dtb
├── sun8i-t3-cqa3t-bv3.dtb
├── sun8i-v3-sl631-imx179.dtb
├── sun8i-v3s-licheepi-zero-dock.dtb
├── sun8i-v3s-licheepi-zero.dtb
├── sun8i-v40-bananapi-m2-berry.dtb
├── sun9i-a80-cubieboard4.dtb
└── sun9i-a80-optimus.dtb

2 directories, 241 files

**Comment by sp2ong** [comment]
armbian-config was that if there is overlay_prefix= in armbianEnv.txt then the list of device modules was shown only for those that have overlay_prefix and not as currently all modules are shown for different platforms e.g. for OZPI I see suni8i-h3- sun4i-a10 etc. which is less readable. If only those that have overlay_prefix in rambianEnv.txt were shown as it used to be it is more readable but this is just a small suggestion from the user's point of view

**Comment by sp2ong** [comment]
Hm

in result: tree /boot/dtb/  I see only

├── sun8i-h3-orangepi-2.dtb
├── sun8i-h3-orangepi-lite.dtb
├── sun8i-h3-orangepi-one.dtb
├── sun8i-h3-orangepi-pc.dtb
├── sun8i-h3-orangepi-pc-plus.dtb
├── sun8i-h3-orangepi-plus2e.dtb
├── sun8i-h3-orangepi-plus.dtb
├── sun8i-h3-orangepi-zero-plus2.dtb

but not exit sun8i-h3-orangepi-zero.dtb  ??? for Ornage Pi Zero v1  is used  sun8i-h3-zeropi.dtb  ???

**Comment by MMinga** [comment]
No on my system it does not work:

> /boot/dtb/
├── overlay
│   ├── README.rk322x-overlays
│   ├── README.rockchip-overlays
│   ├── rk322x-bt-8723cs.dtbo
│   ├── rk322x-cpu-hs.dtbo
│   ├── rk322x-cpu-hs-lv.dtbo
│   ├── rk322x-cpu-stability.dtbo
│   ├── rk322x-ddr3-330.dtbo
│   ├── rk322x-ddr3-528.dtbo
│   ├── rk322x-ddr3-660.dtbo
│   ├── rk322x-ddr3-800.dtbo
│   ├── rk322x-emmc-ddr-ph180.dtbo
│   ├── rk322x-emmc-ddr-ph45.dtbo
│   ├── rk322x-emmc.dtbo
│   ├── rk322x-emmc-hs200.dtbo
│   ├── rk322x-emmc-pins.dtbo
│   ├── rk322x-fixup.scr
│   ├── rk322x-ir-wakeup.dtbo
│   ├── rk322x-led-conf1.dtbo
│   ├── rk322x-led-conf2.dtbo
│   ├── rk322x-led-conf3.dtbo
│   ├── rk322x-led-conf4.dtbo
│   ├── rk322x-led-conf5.dtbo
│   ├── rk322x-led-conf6.dtbo
│   ├── rk322x-led-conf7.dtbo
│   ├── rk322x-led-conf8.dtbo
│   ├── rk322x-led-conf-default.dtbo
│   ├── rk322x-nand.dtbo
│   ├── rk322x-usb-otg-peripheral.dtbo
│   ├── rk322x-wlan-alt-wiring.dtbo
│   ├── rockchip-ds1307.dtbo
│   ├── rockchip-fixup.scr
│   ├── rockchip-i2c1.dtbo
│   ├── rockchip-i2c4.dtbo
│   ├── rockchip-pwm1.dtbo
│   ├── rockchip-pwm2.dtbo
│   ├── rockchip-pwm3.dtbo
│   ├── rockchip-spi0.dtbo
│   ├── rockchip-spi2.dtbo
│   ├── rockchip-spidev0.dtbo
│   ├── rockchip-spidev2.dtbo
│   ├── rockchip-uart1.dtbo
│   ├── rockchip-uart2.dtbo
│   ├── rockchip-uart3.dtbo
│   ├── rockchip-uart4.dtbo
│   └── rockchip-w1-gpio.dtbo
├── rk3036-evb.dtb
├── rk3036-kylin.dtb
├── rk3066a-bqcurie2.dtb
├── rk3066a-marsboard.dtb
├── rk3066a-mk808.dtb
├── rk3066a-rayeager.dtb
├── rk3128-evb.dtb
├── rk3188-bqedison2qc.dtb
├── rk3188-px3-evb.dtb
├── rk3188-radxarock.dtb
├── rk3228-evb.dtb
├── rk3229-evb.dtb
├── rk3229-xms6.dtb
├── rk322x-box.dtb
├── rk3288-evb-act8846.dtb
├── rk3288-evb-rk808.dtb
├── rk3288-firefly-beta.dtb
├── rk3288-firefly.dtb
├── rk3288-firefly-reload.dtb
├── rk3288-miqi.dtb
├── rk3288-phycore-rdk.dtb
├── rk3288-popmetal.dtb
├── rk3288-r89.dtb
├── rk3288-rock2-square.dtb
├── rk3288-rock-pi-n8.dtb
├── rk3288-tinker.dtb
├── rk3288-tinker-s.dtb
├── rk3288-veyron-brain.dtb
├── rk3288-veyron-fievel.dtb
├── rk3288-veyron-jaq.dtb
├── rk3288-veyron-jerry.dtb
├── rk3288-veyron-mickey.dtb
├── rk3288-veyron-mighty.dtb
├── rk3288-veyron-minnie.dtb
├── rk3288-veyron-pinky.dtb
├── rk3288-veyron-speedy.dtb
├── rk3288-veyron-tiger.dtb
├── rk3288-vyasa.dtb
├── rk3288-xt-q8l-v10.dtb
├── rv1108-elgin-r1.dtb
├── rv1108-evb.dtb
└── rv1126-edgeble-neu2-io.dtb

1 directory, 87 files
verbosity=1
extraargs=coherent_pool=2M
bootlogo=false
overlay_prefix=rockchip,rk
overlays=es90x8q2m-dac,i2c1
rootdev=UUID=a39b8cef-c3a4-41d8-a0cf-fe08d139f982
rootfstype=ext4
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u

**Comment by igorpecovnik** [comment]
@The-going Do you have any idea what we messed up here?

**Comment by The-going** [comment]
> overlay_prefix=rockchip,rk

Incorrect prefix.
In your case, it could be:
overlay_prefix=rockchip
or
overlay_prefix=rk322x

**Comment by igorpecovnik** [comment]
> Incorrect prefix.

I assume this is user error? I just want to make sure our part (build framework) and armbian-config works well?

**Comment by sp2ong** [comment]
But I have on my Orange Pi Zero V1

_overlay_prefix=sun8i-h3
overlays=sun8i-h3-analog-codec sun8i-h3-i2c0 sun8i-h3-uart1 sun8i-h3-uart2 sun8i-h3-usbhost2 sun8i-h3-usbhost3_

and when is added overlay prefix in overlays modules not loaded

**Comment by The-going** [comment]
> > Incorrect prefix.
> 
> I assume this is user error? I just want to make sure our part (build framework) and armbian-config works well?

We do not list the overlay prefix in any download script.
There can only be one overlay prefix.

This is user error.

**Comment by The-going** [comment]
> But I have on my Orange Pi Zero V1
> 
> _overlay_prefix=sun8i-h3 overlays=sun8i-h3-analog-codec sun8i-h3-i2c0 sun8i-h3-uart1 sun8i-h3-uart2 sun8i-h3-usbhost2 sun8i-h3-usbhost3_
> 
> and when is added overlay prefix in overlays modules not loaded

**_uname -r_**

**Comment by sp2ong** [comment]
uname -r
6.6.72-current-sunxi

**Comment by sp2ong** [comment]
I sent my all information yesterday: https://github.com/armbian/configng/issues/344#issuecomment-2611696552

**Comment by sp2ong** [comment]
I use image https://www.armbian.com/orange-pi-zero/

Minimal/IOT images with Armbian Linux v6.6

Build Date: Jan 23, 2025

which updated

**Comment by The-going** [comment]
> overlays=sun8i-h3-analog-codec sun8i-h3-i2c0 sun8i-h3-uart1 sun8i-h3-uart2 sun8i-h3-usbhost2 sun8i-h3-usbhost3

Valid:
```
overlay_prefix=sun8i-h3
overlays=analog-codec i2c0 uart1 uart2 usbhost2 usbhost3
```
Name DTBO:  ${overlay_prefix}-${overlay_file}.dtbo
See: 
[load fdt](https://github.com/armbian/build/blob/fbd8c8e4c904c31d2bcbcd77ff7b240c8a2f2175/config/bootscripts/boot-sunxi.cmd#L106)

**Comment by sp2ong** [comment]
Yes, when no exist overly prefix in overlays is all working but armbian-config when I manage Overlays added overlay prefix to overlays

**Comment by The-going** [comment]
> when selecting Manage oerlays from armbian-config not see my selected modules in overlays= in armbianEnv.txt so I selected again but still added overlay_prefix to modules in overlays= and after reboot no modules loaded. When removing manually overlay prefix form names modules in overlaus= all works

@igorpecovnik This looks like an error in the armbian config script.

**Comment by sp2ong** [comment]
I and others wrote about this at: https://github.com/armbian/configng/issues/360

**Comment by sp2ong** [comment]
Similar problem with latest armbian-config NG exit on Orange Pi Zero 3 with Bookworm Armbian Image which is updated and armbian-config add overlay prefix to overlays which causes modules not to load, I must have to manually remove overly prefix in amrbianEnv.txt

**Comment by igorpecovnik** [comment]
> This looks like an error in the armbian config script.

Am I blind, but I don't see any problems here. Prefix is not touched - it has to set right at build time.

https://github.com/armbian/configng/blob/main/tools/modules/system/manage_dtoverlays.sh#L48-L50

**Comment by The-going** [comment]
> > This looks like an error in the armbian config script.
> 
> Am I blind, but I don't see any problems here. Prefix is not touched - it has to set right at build time.
> 
> https://github.com/armbian/configng/blob/main/tools/modules/system/manage_dtoverlays.sh#L48-L50

Okay, I'll take a look tonight.
Now I want to finish the BPI-M4-Berry.

**Comment by MMinga** [comment]
> > overlay_prefix=rockchip,rk
> 
> Incorrect prefix. In your case, it could be: overlay_prefix=rockchip or overlay_prefix=rk322x

Corrected but also the overlays are not shown.

`/boot/dtb/
├── overlay
│   ├── README.rk322x-overlays
│   ├── README.rockchip-overlays
│   ├── rk322x-bt-8723cs.dtbo
│   ├── rk322x-cpu-hs.dtbo
│   ├── rk322x-cpu-hs-lv.dtbo
│   ├── rk322x-cpu-stability.dtbo
│   ├── rk322x-ddr3-330.dtbo
│   ├── rk322x-ddr3-528.dtbo
│   ├── rk322x-ddr3-660.dtbo
│   ├── rk322x-ddr3-800.dtbo
│   ├── rk322x-emmc-ddr-ph180.dtbo
│   ├── rk322x-emmc-ddr-ph45.dtbo
│   ├── rk322x-emmc.dtbo
│   ├── rk322x-emmc-hs200.dtbo
│   ├── rk322x-emmc-pins.dtbo
│   ├── rk322x-fixup.scr
│   ├── rk322x-ir-wakeup.dtbo
│   ├── rk322x-led-conf1.dtbo
│   ├── rk322x-led-conf2.dtbo
│   ├── rk322x-led-conf3.dtbo
│   ├── rk322x-led-conf4.dtbo
│   ├── rk322x-led-conf5.dtbo
│   ├── rk322x-led-conf6.dtbo
│   ├── rk322x-led-conf7.dtbo
│   ├── rk322x-led-conf8.dtbo
│   ├── rk322x-led-conf-default.dtbo
│   ├── rk322x-nand.dtbo
│   ├── rk322x-usb-otg-peripheral.dtbo
│   ├── rk322x-wlan-alt-wiring.dtbo
│   ├── rockchip-ds1307.dtbo
│   ├── rockchip-fixup.scr
│   ├── rockchip-i2c1.dtbo
│   ├── rockchip-i2c4.dtbo
│   ├── rockchip-pwm1.dtbo
│   ├── rockchip-pwm2.dtbo
│   ├── rockchip-pwm3.dtbo
│   ├── rockchip-spi0.dtbo
│   ├── rockchip-spi2.dtbo
│   ├── rockchip-spidev0.dtbo
│   ├── rockchip-spidev2.dtbo
│   ├── rockchip-uart1.dtbo
│   ├── rockchip-uart2.dtbo
│   ├── rockchip-uart3.dtbo
│   ├── rockchip-uart4.dtbo
│   └── rockchip-w1-gpio.dtbo
├── rk3036-evb.dtb
├── rk3036-kylin.dtb
├── rk3066a-bqcurie2.dtb
├── rk3066a-marsboard.dtb
├── rk3066a-mk808.dtb
├── rk3066a-rayeager.dtb
├── rk3128-evb.dtb
├── rk3188-bqedison2qc.dtb
├── rk3188-px3-evb.dtb
├── rk3188-radxarock.dtb
├── rk3228-evb.dtb
├── rk3229-evb.dtb
├── rk3229-xms6.dtb
├── rk322x-box.dtb
├── rk3288-evb-act8846.dtb
├── rk3288-evb-rk808.dtb
├── rk3288-firefly-beta.dtb
├── rk3288-firefly.dtb
├── rk3288-firefly-reload.dtb
├── rk3288-miqi.dtb
├── rk3288-phycore-rdk.dtb
├── rk3288-popmetal.dtb
├── rk3288-r89.dtb
├── rk3288-rock2-square.dtb
├── rk3288-rock-pi-n8.dtb
├── rk3288-tinker.dtb
├── rk3288-tinker-s.dtb
├── rk3288-veyron-brain.dtb
├── rk3288-veyron-fievel.dtb
├── rk3288-veyron-jaq.dtb
├── rk3288-veyron-jerry.dtb
├── rk3288-veyron-mickey.dtb
├── rk3288-veyron-mighty.dtb
├── rk3288-veyron-minnie.dtb
├── rk3288-veyron-pinky.dtb
├── rk3288-veyron-speedy.dtb
├── rk3288-veyron-tiger.dtb
├── rk3288-vyasa.dtb
├── rk3288-xt-q8l-v10.dtb
├── rv1108-elgin-r1.dtb
├── rv1108-evb.dtb
└── rv1126-edgeble-neu2-io.dtb

1 directory, 87 files
verbosity=1
extraargs=coherent_pool=2M
bootlogo=false
overlay_prefix=rockchip
overlays=es90x8q2m-dac,i2c1
rootdev=UUID=a39b8cef-c3a4-41d8-a0cf-fe08d139f982
rootfstype=ext4
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u

`

![Image](https://github.com/user-attachments/assets/643eb7cf-9bf8-444a-9c11-41ba86eaa222)

**Comment by igorpecovnik** [comment]
> Corrected but also the overlays are not shown.

Probably because you manually added es90x8q2m-dac which does not exists?

**Comment by The-going** [comment]
> overlay_prefix=rockchip
> overlays=es90x8q2m-dac,i2c1

Valid:
```
overlay_prefix=rockchip
overlays=i2c1
```
**_overlays=name1 name2 name3 name4_**
names are separated by a space. The name must exist.

**Comment by sp2ong** [comment]
> > This looks like an error in the armbian config script.
> 
> Am I blind, but I don't see any problems here. Prefix is not touched - it has to set right at build time.
> 
> https://github.com/armbian/configng/blob/main/tools/modules/system/manage_dtoverlays.sh#L48-L50

Hi, old armbin-config not NG when we go to select hardware show as all modules where names was without overlay_prefix and show only modules which has overlay prefix. When we select  modules and SAVE in armbianEnv.txt overlyas= was with overlays prefix. The armbian-congig NG new when we select SYS210 "Manage device tree overlays" show all modules where names included overlay prefix so I suppose for this reason when we select modules and SAVE in armbiaEnv.txt in overlays= are saved modules with overlay prefix for example sun8i-h3-analog-code but shuld be with overlay prefix

![Image](https://github.com/user-attachments/assets/fc7927d4-0c3d-4169-87b4-0b2e2f8eaa5f)

**Comment by sp2ong** [comment]
According code: https://github.com/armbian/configng/blob/main/tools/modules/system/manage_dtoverlays.sh#L48-L50

`newoverlays=$(echo $selection | sed 's/"//g')`

simple test if name is **sun8i-h3-analog-codec**  result this code:

echo sun8i-h3-analog-codec |sed 's/"//g'
**sun8i-h3-analog-codec**

so this name is stored in armbianEnv.txt

but I suppose should be **analog-codec**

**Comment by sp2ong** [comment]
Look on old armbian-config:  https://github.com/armbian/config/blob/473f9990fe722bc7fa2c77795f50dea3118708ff/debian-config-jobs#L1210
It looks like during load overlays to display in menu was striped overlay_prefix (defined in armbianEnv.txt for this reason displayed overlays was without prefix so if this name was without prefix it was stored in armbianEnv.txt in overlays= without overlay prefix and all works

For me when i armbian-config NG should be prepared list of overlays similar and should be display only overlays which has overla_prefix in name overlay

but I am not programs

**Comment by sp2ong** [comment]
When I use code with old armbian-config to prepare list of overlay

def_overlays=$(ls -1 ${OVERLAYDIR}/${overlay_prefix}*.dtbo | sed 's/^.*\('${overlay_prefix}'.*\)/\1/g' | sed 's/'${overlay_prefix}'-//g' | sed 's/.dtbo//g')

result for overlay_prefix=sun8i-h3

ls -1 /boot/dtb/overlay/sun8i-h3*.dtbo | sed 's/^.*\('sun8i-h3'.*\)/\1/g' | sed 's/'sun8i-h3'-//g' | sed 's/.dtbo//g'
analog-codec
cir
cpu-clock-1.2GHz-1.3v
cpu-clock-1.368GHz-1.3v
cpu-clock-1.3GHz-1.3v
i2c0
i2c1
i2c2
pps-gpio
pwm
spdif-out
spi-add-cs1
spi-jedec-nor
spi-spidev
tve
uart1
uart2
uart3
usbhost0
usbhost1
usbhost2
usbhost3
w1-gpio


so we have overlays names without overlay prefix and displayed only for sun8i-h3

**Comment by sp2ong** [comment]
In new armbian-config list of overlays is created

`available_overlays=$(ls -1 ${overlaydir}/*.dtbo | sed "s#^${overlaydir}/##" | sed 's/.dtbo//g' | grep -E "$BOOT_SOC|$BOARD" | tr '\n' ' ')`

so result this code is

ls -1 /boot/dtb/overlay/*.dtbo | sed "s#^/boot/dtb/overlay/##" | sed 's/.dtbo//g' | grep -E "$BOOT_SOC|$BOARD" | tr '\n' ' '
sun4i-a10-analog-codec sun4i-a10-can sun4i-a10-i2c1 sun4i-a10-i2c2 sun4i-a10-nand sun4i-a10-pps-gpio sun4i-a10-pwm sun4i-a10-spdif-out sun4i-a10-spi-jedec-nor sun4i-a10-spi-spidev sun4i-a10-uart2 sun4i-a10-uart3 sun4i-a10-uart4 sun4i-a10-uart5 sun4i-a10-uart6 sun4i-a10-uart7 sun4i-a10-w1-gpio sun5i-a13-analog-codec sun5i-a13-i2c1 sun5i-a13-i2c2 sun5i-a13-nand sun5i-a13-pwm sun5i-a13-spi0 sun5i-a13-spi1 sun5i-a13-spi2 sun5i-a13-spi-jedec-nor sun5i-a13-spi-spidev sun5i-a13-uart0 sun5i-a13-uart1 sun5i-a13-uart2 sun5i-a13-uart3 sun7i-a20-analog-codec sun7i-a20-can sun7i-a20-i2c1 sun7i-a20-i2c2 sun7i-a20-i2c3 sun7i-a20-i2c4 sun7i-a20-mmc2 sun7i-a20-nand sun7i-a20-pps-gpio sun7i-a20-pwm sun7i-a20-spdif-out sun7i-a20-spi-add-cs1 sun7i-a20-spi-jedec-nor sun7i-a20-spi-spidev sun7i-a20-uart2 sun7i-a20-uart3 sun7i-a20-uart4 sun7i-a20-uart5 sun7i-a20-uart6 sun7i-a20-uart7 sun7i-a20-w1-gpio sun8i-h3-analog-codec sun8i-h3-cir sun8i-h3-cpu-clock-1.2GHz-1.3v sun8i-h3-cpu-clock-1.368GHz-1.3v sun8i-h3-cpu-clock-1.3GHz-1.3v sun8i-h3-i2c0 sun8i-h3-i2c1 sun8i-h3-i2c2 sun8i-h3-pps-gpio sun8i-h3-pwm sun8i-h3-spdif-out sun8i-h3-spi-add-cs1 sun8i-h3-spi-jedec-nor sun8i-h3-spi-spidev sun8i-h3-tve sun8i-h3-uart1 sun8i-h3-uart2 sun8i-h3-uart3 sun8i-h3-usbhost0 sun8i-h3-usbhost1 sun8i-h3-usbhost2 sun8i-h3-usbhost3 sun8i-h3-w1-gpio sun8i-r40-i2c2 sun8i-r40-i2c3 sun8i-r40-spi-spidev0 sun8i-r40-spi-spidev1 sun8i-r40-uart2 sun8i-r40-uart4 sun8i-r40-uart5 sun8i-r40-uart7


long list all overlays which we see in menu overlays in armbian-config, I am not sure about grep -E "$BOOT_SOC|$BOARD"   where is defined

**Comment by igorpecovnik** [comment]
Thank you for help. I think this is it, but need more testing: https://github.com/armbian/configng/pull/393

**Comment by sp2ong** [comment]
Ok no problem, it looks like new armbian-config not use overlay_prefix= from amrmbianEnv.txt which help to reduce displayed overlays to manage and strip this name in overlays. If you create new version armbin-config I will be check.

Regards
Waldek

**Comment by sp2ong** [comment]
Ah I see variable $BOARD_SOC and $BOARD is coming from /etc/armbian-image-release but on Orange Pi Zero BOARD_SOC is empty and BOARD is orangepizro but it is not match in names in overlays so old method which used overlay_prefox form amrmbianEnv.txt works quite good according to doc ArmBian: https://docs.armbian.com/User-Guide_Armbian_overlays/  `overlay_prefix - prefix for the DT and overlay file names, set at OS image creation time`

_if [[ -n "${BOOT_SOC}" ]]; then
available_overlays=$(ls -1 ${overlaydir}/*.dtbo | sed "s#^${overlaydir}/##" | sed 's/.dtbo//g' | grep -E "$BOOT_SOC|$BOARD" | tr '\n' ' ')
else
available_overlays=$(ls -1 ${overlaydir}/*.dtbo | sed "s#^${overlaydir}/##" | sed 's/.dtbo//g' | tr '\n' ' ')
 fi_

**Comment by igorpecovnik** [comment]
This should be fixed now, closing. Reopen in case of troubles.

**Comment by MMinga** [comment]
It does still not work on my system, where is my fault, if so?
HW: tinkerboard 
```/boot/dtb/
├── overlay
│   ├── README.rk322x-overlays
│   ├── README.rockchip-overlays
│   ├── rk322x-bt-8723cs.dtbo
│   ├── rk322x-cpu-hs.dtbo
│   ├── rk322x-cpu-hs-lv.dtbo
│   ├── rk322x-cpu-stability.dtbo
│   ├── rk322x-ddr3-330.dtbo
│   ├── rk322x-ddr3-528.dtbo
│   ├── rk322x-ddr3-660.dtbo
│   ├── rk322x-ddr3-800.dtbo
│   ├── rk322x-emmc-ddr-ph180.dtbo
│   ├── rk322x-emmc-ddr-ph45.dtbo
│   ├── rk322x-emmc.dtbo
│   ├── rk322x-emmc-hs200.dtbo
│   ├── rk322x-emmc-pins.dtbo
│   ├── rk322x-fixup.scr
│   ├── rk322x-ir-wakeup.dtbo
│   ├── rk322x-led-conf1.dtbo
│   ├── rk322x-led-conf2.dtbo
│   ├── rk322x-led-conf3.dtbo
│   ├── rk322x-led-conf4.dtbo
│   ├── rk322x-led-conf5.dtbo
│   ├── rk322x-led-conf6.dtbo
│   ├── rk322x-led-conf7.dtbo
│   ├── rk322x-led-conf8.dtbo
│   ├── rk322x-led-conf-default.dtbo
│   ├── rk322x-nand.dtbo
│   ├── rk322x-usb-otg-peripheral.dtbo
│   ├── rk322x-wlan-alt-wiring.dtbo
│   ├── rockchip-ds1307.dtbo
│   ├── rockchip-es90x8q2m-dac.dtbo
│   ├── rockchip-fixup.scr
│   ├── rockchip-i2c1.dtbo
│   ├── rockchip-i2c4.dtbo
│   ├── rockchip-pwm1.dtbo
│   ├── rockchip-pwm2.dtbo
│   ├── rockchip-pwm3.dtbo
│   ├── rockchip-spi0.dtbo
│   ├── rockchip-spi2.dtbo
│   ├── rockchip-spidev0.dtbo
│   ├── rockchip-spidev2.dtbo
│   ├── rockchip-uart1.dtbo
│   ├── rockchip-uart2.dtbo
│   ├── rockchip-uart3.dtbo
│   ├── rockchip-uart4.dtbo
│   └── rockchip-w1-gpio.dtbo
├── rk3036-evb.dtb
├── rk3036-kylin.dtb
├── rk3066a-bqcurie2.dtb
├── rk3066a-marsboard.dtb
├── rk3066a-mk808.dtb
├── rk3066a-rayeager.dtb
├── rk3128-evb.dtb
├── rk3188-bqedison2qc.dtb
├── rk3188-px3-evb.dtb
├── rk3188-radxarock.dtb
├── rk3228-evb.dtb
├── rk3229-evb.dtb
├── rk3229-xms6.dtb
├── rk322x-box.dtb
├── rk3288-evb-act8846.dtb
├── rk3288-evb-rk808.dtb
├── rk3288-firefly-beta.dtb
├── rk3288-firefly.dtb
├── rk3288-firefly-reload.dtb
├── rk3288-miqi.dtb
├── rk3288-phycore-rdk.dtb
├── rk3288-popmetal.dtb
├── rk3288-r89.dtb
├── rk3288-rock2-square.dtb
├── rk3288-rock-pi-n8.dtb
├── rk3288-tinker.dtb
├── rk3288-tinker-s.dtb
├── rk3288-veyron-brain.dtb
├── rk3288-veyron-fievel.dtb
├── rk3288-veyron-jaq.dtb
├── rk3288-veyron-jerry.dtb
├── rk3288-veyron-mickey.dtb
├── rk3288-veyron-mighty.dtb
├── rk3288-veyron-minnie.dtb
├── rk3288-veyron-pinky.dtb
├── rk3288-veyron-speedy.dtb
├── rk3288-veyron-tiger.dtb
├── rk3288-vyasa.dtb
├── rk3288-xt-q8l-v10.dtb
├── rv1108-elgin-r1.dtb
├── rv1108-evb.dtb
└── rv1126-edgeble-neu2-io.dtb

1 directory, 88 files
verbosity=1
extraargs=coherent_pool=2M
bootlogo=false
overlay_prefix=rockchip
overlays=es90x8q2m-dac i2c1
rootdev=UUID=a39b8cef-c3a4-41d8-a0cf-fe08d139f982
rootfstype=ext4
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u

**Comment by apex-cmyk** [comment]
You can have a try of the Yajuzhen CloudPhone（亚矩阵云手机）. They are now using RK3588.
